### ISSUE TITLE
Can not access unity with vnc

### ISSUE THREAD

**Issue by UltraREX** [nenadg/docker-unity3d#4]
I was successfully run unity-service, but I can not access unity with vnc. Could you give me some advice on how to access it correctly? Thx a lot.

**Comment by UltraREX** [comment]
step 1: git clone https://github.com/nenadg/docker-unity3d.git
step 2: cd docker-unity3d
step 3: docker-compose up -d
step 4: use vnc to access it

then failed

**Comment by nenadg** [comment]
AFAIK, you should connect to `172.16.250.10` with password `pass123` (as configured in docker-compose.yml), if that fails connect to container `docker exec -it unity-service bash` and check if vnc is started with `ps aux`. 

Sorry I don't have this container built on current computer so this is as much help as I can give right now.

**Comment by UltraREX** [comment]
I success access it with vnc right now. I connect to localhost with the password, not the IP 172.16.250.10.
But I don' t know why.

I execute `docker ps -a` in the terminal. It show
PORTS 0.0.0.0:5555->5555/tcp, 0.0.0.0:5900->5900/tcp

**Comment by nenadg** [comment]
Okay, you can access by localhost as well. Which OS do you use?

**Comment by UltraREX** [comment]
Thx.
The OS I use is macOS high sierra.

**Comment by nenadg** [comment]
Yeah, I though that might be the case. I wrote the README with Linux on my mind, Docker on MacOS behaves somewhat different (ie. you can't map internal IP, but can map port to localhost/0.0.0.0). 

I'm glad we solved this :)

**Comment by UltraREX** [comment]
✌️👍

**Comment by lilyzhng** [comment]
I am having the same issue. Could you clarify that what is the user name?

**Comment by nenadg** [comment]
@alchemz I'm using VNC client that doesn't prompt me for username. As you can see from configuration files I also set none.

You can try ```root``` since it's default docker's user.
