### ISSUE TITLE
VNC Issue

### ISSUE THREAD

**Issue by lilyzhng** [nenadg/docker-unity3d#5]
The 5900 port is allocated on my computer already. So I changed port setting in the docker-compose.yml file and Dockerfile.

RUN docker ps
CONTAINER ID        IMAGE                  COMMAND             CREATED             STATUS              PORTS                                                      NAMES
d445ef4a58fe        docker-unity3d_unity   "/entrypoint.sh"    6 minutes ago       Up 6 minutes        0.0.0.0:5555->5555/tcp, 0.0.0.0:5910->5910/tcp, 5900/tcp   unity-service

RUN  ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
adminus+     1  0.0  0.1  18028  2760 pts/0    Ss+  01:01   0:00 /bin/bash /entr
adminus+     9  0.1  0.2  98860  5816 pts/0    S+   01:01   0:00 x11vnc -forever
adminus+    10  0.2  0.1  18220  3204 pts/1    Ss   01:05   0:00 bash
adminus+    18  0.0  0.1  34420  2828 pts/1    R+   01:05   0:00 ps aux

**Comment by lilyzhng** [comment]
I am using a Mac, so 172.16.250.10 does not work for me, instead, I used localhost to start the VNC viewer.

Yet it asked me the username and password. I know the password is pass123, but what is the username?

**Comment by nenadg** [comment]
Try https://github.com/nenadg/docker-unity3d/issues/4#issuecomment-444709919

**Comment by lilyzhng** [comment]
@nenadg Thank you very much for the reply, I have tried multiple user names, including 
- root
- adminus+
- None
- admin

but none of the above worked.

**Comment by lilyzhng** [comment]
The window popped for credentials contains the following info,
" Enter the credentials expected by VNC Server running on the remote computer.
Note these are not your RealVNC account credentials.

VNC Server: localhost::5900
Username:
Password:
"

which does not look right, because as the docker message shown above, I configured the port to 5910.

**Comment by nenadg** [comment]
note that adminus+ is just a way your console abbreviates ```adminuser```, you can try that.

Tomorrow, I'll try to figure this out in more depth since I don't have working image on this machine.
